modLoader = "javafml"
loaderVersion= "[36,)"
license = "MIT"

[[mods]]
modId = "replanter"
version = "1.2"
displayName = "Replanter"
displayURL= "https://www.curseforge.com/minecraft/mc-mods/replanter"
issueTrackerURL = "https://github.com/kregerl/Replanter"
logoFile = "replanter.png"
credits =""
authors = "AreUThreateningMe"
description = '''
Replanter is a client side mod that allows players to right click on crops to harvest and replant them.
'''

[[dependencies.replanter]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.replanter]]
modId = "minecraft"
mandatory= true
versionRange = "[1.17.1, 1.18)"
ordering = "AFTER"
side ="BOTH"
